### PR TITLE
Improved jump to run transition.

### PR DESCRIPTION
**Pull request by Sartech-B**

### CODE REVIEW

**Review by dgkanatsios — COMMENTED** [review]
Can you please describe the changes?

**Comment by Sartech-B** [comment]
Well, previously when the character used to jump the animation did not transition properly to run and it looked weird, I changed that and also the camera angle!

**Comment by dgkanatsios** [comment]
Thank you. Since the files are in binary format (will change that in the next commit), I cannot see the differences (i.e. what exactly you changed in the animator controller), can you describe? Reason I'm asking is to see whether I need to change the blog posts accompanying this game demo.

**Comment by Sartech-B** [comment]
I changed the transitioning from jump animation to run animation in the animator controller.

**Comment by Sartech-B** [comment]
Thanks man, for merging.

**Pull request merged**
